module.exports = {
  mySidebar: [
    {
      type: "category",
      label: "Setup",
      items: [
        {
          type: "autogenerated",
          dirName: "01-basics",
        },
      ],
    },
    {
      type: "category",
      label: "Core Concepts",
      items: [
        {
          type: "autogenerated",
          dirName: "03-guides",
        },
      ],
    },
    {
      type: "category",
      label: "UI Components",
      items: [
        {
          type: "autogenerated",
          dirName: "04-ui-components",
        },
      ],
    },

    {
      type: "category",
      label: "UI Cookbook",
      items: [
        {
          type: "autogenerated",
          dirName: "05-ui-cookbook",
        },
      ],
    },
    {
      type: "category",
      label: "Advanced Guides",
      items: [
        {
          type: "autogenerated",
          dirName: "06-advanced",
        },
      ],
    },
    {
      type: "category",
      label: "Playground",
      items: [
        {
          type: "autogenerated",
          dirName: "07-playground",
        },
      ],
    },
  ],
};
