module.exports = {
  mySidebar: [
    {
      type: "category",
      label: "Basics",
      items: [
        {
          type: "autogenerated",
          dirName: "01-basics",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      items: [
        {
          type: "autogenerated",
          dirName: "02-guides",
        },
      ],
    },
    {
      type: "category",
      label: "Video UI Components",
      items: [
        {
          type: "autogenerated",
          dirName: "03-ui",
        },
      ],
    },
    {
      type: "category",
      label: "Client",
      items: [
        {
          type: "autogenerated",
          dirName: "04-client",
        },
      ],
    },
    {
      type: "category",
      label: "Advanced Guides",
      items: [
        {
          type: "autogenerated",
          dirName: "05-advanced",
        },
      ],
    },
  ],
};
