// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: video/coordinator/server_v1_rpc/envelopes.proto

package server_v1_rpc

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ExportUserEnvelope with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ExportUserEnvelope) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExportUserEnvelope with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExportUserEnvelopeMultiError, or nil if none found.
func (m *ExportUserEnvelope) ValidateAll() error {
	return m.validate(true)
}

func (m *ExportUserEnvelope) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUser()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExportUserEnvelopeValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExportUserEnvelopeValidationError{
					field:  "User",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUser()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExportUserEnvelopeValidationError{
				field:  "User",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetCalls() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ExportUserEnvelopeValidationError{
						field:  fmt.Sprintf("Calls[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ExportUserEnvelopeValidationError{
						field:  fmt.Sprintf("Calls[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ExportUserEnvelopeValidationError{
					field:  fmt.Sprintf("Calls[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	{
		sorted_keys := make([]string, len(m.GetMembers()))
		i := 0
		for key := range m.GetMembers() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetMembers()[key]
			_ = val

			// no validation rules for Members[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, ExportUserEnvelopeValidationError{
							field:  fmt.Sprintf("Members[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, ExportUserEnvelopeValidationError{
							field:  fmt.Sprintf("Members[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return ExportUserEnvelopeValidationError{
						field:  fmt.Sprintf("Members[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	for idx, item := range m.GetRecordings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ExportUserEnvelopeValidationError{
						field:  fmt.Sprintf("Recordings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ExportUserEnvelopeValidationError{
						field:  fmt.Sprintf("Recordings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ExportUserEnvelopeValidationError{
					field:  fmt.Sprintf("Recordings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ExportUserEnvelopeMultiError(errors)
	}

	return nil
}

// ExportUserEnvelopeMultiError is an error wrapping multiple validation errors
// returned by ExportUserEnvelope.ValidateAll() if the designated constraints
// aren't met.
type ExportUserEnvelopeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExportUserEnvelopeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExportUserEnvelopeMultiError) AllErrors() []error { return m }

// ExportUserEnvelopeValidationError is the validation error returned by
// ExportUserEnvelope.Validate if the designated constraints aren't met.
type ExportUserEnvelopeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExportUserEnvelopeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExportUserEnvelopeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExportUserEnvelopeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExportUserEnvelopeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExportUserEnvelopeValidationError) ErrorName() string {
	return "ExportUserEnvelopeValidationError"
}

// Error satisfies the builtin error interface
func (e ExportUserEnvelopeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExportUserEnvelope.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExportUserEnvelopeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExportUserEnvelopeValidationError{}
