blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/GetStream/stream-video-android/discussions
    about: If you just have a question, please open a discussion instead of an issue.
