/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models





import com.squareup.moshi.Json

/**
 * 
 *
 * @param accessRequestEnabled 
 * @param opusDtxEnabled 
 * @param redundantCodingEnabled 
 */


data class AudioSettings (

    @Json(name = "access_request_enabled")
    val accessRequestEnabled: kotlin.Boolean,

    @Json(name = "opus_dtx_enabled")
    val opusDtxEnabled: kotlin.Boolean,

    @Json(name = "redundant_coding_enabled")
    val redundantCodingEnabled: kotlin.Boolean

)


