/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.HLSSettings




import com.squareup.moshi.Json

/**
 * 
 *
 * @param enabled 
 * @param hls 
 */


data class BroadcastSettings (

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "hls")
    val hls: HLSSettings

)




