/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserResponse




import com.squareup.moshi.Json

/**
 * 
 *
 * @param joinedAt 
 * @param user 
 */


data class CallParticipantResponse (

    @Json(name = "joined_at")
    val joinedAt: org.threeten.bp.OffsetDateTime,

    @Json(name = "user")
    val user: UserResponse

)




