/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CallResponse
import org.openapitools.client.models.UserResponse




import com.squareup.moshi.Json

/**
 * This event is sent when a user accepts a notification to join a call.
 *
 * @param call 
 * @param callCid 
 * @param createdAt 
 * @param type The type of event: \"call.accepted\" in this case
 * @param user 
 */


data class CallAcceptedEvent (

    @Json(name = "call")
    val call: CallResponse,

    @Json(name = "call_cid")
    val callCid: kotlin.String,

    @Json(name = "created_at")
    val createdAt: org.threeten.bp.OffsetDateTime,

    /* The type of event: \"call.accepted\" in this case */
    @Json(name = "type")
    val type: kotlin.String = "call.accepted",

    @Json(name = "user")
    val user: UserResponse

) : VideoEvent(), WSCallEvent{ 

    override fun getCallCID(): String {
        return callCid
    }

    override fun getEventType(): String {
        return type
    }
}



