/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AudioSettings
import org.openapitools.client.models.BackstageSettings
import org.openapitools.client.models.BroadcastSettings
import org.openapitools.client.models.GeofenceSettings
import org.openapitools.client.models.RecordSettings
import org.openapitools.client.models.RingSettings
import org.openapitools.client.models.ScreensharingSettings
import org.openapitools.client.models.TranscriptionSettings
import org.openapitools.client.models.VideoSettings




import com.squareup.moshi.Json

/**
 * 
 *
 * @param audio 
 * @param backstage 
 * @param broadcasting 
 * @param geofencing 
 * @param recording 
 * @param ring 
 * @param screensharing 
 * @param transcription 
 * @param video 
 */


data class CallSettingsResponse (

    @Json(name = "audio")
    val audio: AudioSettings,

    @Json(name = "backstage")
    val backstage: BackstageSettings,

    @Json(name = "broadcasting")
    val broadcasting: BroadcastSettings,

    @Json(name = "geofencing")
    val geofencing: GeofenceSettings,

    @Json(name = "recording")
    val recording: RecordSettings,

    @Json(name = "ring")
    val ring: RingSettings,

    @Json(name = "screensharing")
    val screensharing: ScreensharingSettings,

    @Json(name = "transcription")
    val transcription: TranscriptionSettings,

    @Json(name = "video")
    val video: VideoSettings

)


