/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.UserResponse




import com.squareup.moshi.Json

/**
 * 
 *
 * @param accessToken the access token to authenticate the user
 * @param duration 
 * @param user 
 */


data class CreateGuestResponse (

    /* the access token to authenticate the user */
    @Json(name = "access_token")
    val accessToken: kotlin.String,

    @Json(name = "duration")
    val duration: kotlin.String,

    @Json(name = "user")
    val user: UserResponse

)




