/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CallRequest

import com.squareup.moshi.Json

/**
 * 
 *
 * @param create if true the call will be created if it doesn't exist
 * @param `data` 
 * @param datacenterHintedId 
 * @param membersLimit 
 * @param ring if true and the call is created, the notification will include ring=true
 */


data class JoinCallRequest (

    /* if true the call will be created if it doesn't exist */
    @Json(name = "create")
    val create: kotlin.Boolean? = null,

    @Json(name = "data")
    val `data`: CallRequest? = null,

    @Json(name = "datacenter_hinted_id")
    val datacenterHintedId: kotlin.String? = null,

    @Json(name = "members_limit")
    val membersLimit: kotlin.Int? = null,

    /* if true and the call is created, the notification will include ring=true */
    @Json(name = "ring")
    val ring: kotlin.Boolean? = null

)

