/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param idGt 
 * @param idGte 
 * @param idLt 
 * @param idLte 
 * @param limit 
 * @param offset 
 */


internal data class PaginationParamsRequest (

    @Json(name = "id_gt")
    val idGt: java.math.BigDecimal? = null,

    @Json(name = "id_gte")
    val idGte: java.math.BigDecimal? = null,

    @Json(name = "id_lt")
    val idLt: java.math.BigDecimal? = null,

    @Json(name = "id_lte")
    val idLte: java.math.BigDecimal? = null,

    @Json(name = "limit")
    val limit: java.math.BigDecimal? = null,

    @Json(name = "offset")
    val offset: java.math.BigDecimal? = null

)

