/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models





import com.squareup.moshi.Json

/**
 * 
 *
 * @param direction 
 * @param `field` 
 */


data class SortParamRequest (

    @Json(name = "direction")
    val direction: kotlin.Int? = null,

    @Json(name = "field")
    val `field`: kotlin.String? = null

)




