/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OwnCapability
import org.openapitools.client.models.UserResponse




import com.squareup.moshi.Json

/**
 * This event is sent to notify about permission changes for a user, clients receiving this event should update their UI accordingly
 *
 * @param callCid 
 * @param createdAt 
 * @param ownCapabilities The capabilities of the current user
 * @param type The type of event: \"call.permissions_updated\" in this case
 * @param user 
 */


data class UpdatedCallPermissionsEvent (

    @Json(name = "call_cid")
    val callCid: kotlin.String,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* The capabilities of the current user */
    @Json(name = "own_capabilities")
    val ownCapabilities: kotlin.collections.List<OwnCapability>,

    /* The type of event: \"call.permissions_updated\" in this case */
    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "user")
    val user: UserResponse

): VideoEvent(), WSCallEvent{ 
    override fun getCallCID(): String {
        return callCid
    }

    override fun getEventType(): String {
        return type
    }
}


