default_platform :android
skip_docs

require 'json'
require 'net/http'

@force_check = false

before_all do |lane|
  if is_ci
    setup_ci
    setup_git_config
  end
end

lane :run_sonar_analysis do |options|
  next unless is_check_required(sources: sources_matrix[:sonar], force_check: @force_check)

  Dir.chdir('..') { sh('./gradlew sonar') }
end

desc 'Run fastlane linting'
lane :rubocop do
  next unless is_check_required(sources: sources_matrix[:ruby], force_check: @force_check)

  sh('bundle exec rubocop')
end

private_lane :sources_matrix do
  {
    sonar: ['stream-video-android-'],
    ruby: ['fastlane', 'Gemfile', 'Gemfile.lock']
  }
end
