default_platform :ios
skip_docs

require 'json'
require 'net/http'
import 'Allurefile'

github_repo = ENV['GITHUB_REPOSITORY'] || 'GetStream/stream-video-android'
sinatra_port = 4568
video_buddy_port = 5679
is_localhost = !is_ci
@force_check = false

before_all do |lane|
  if is_ci
    setup_ci
  elsif lane == :test_e2e
    clean_up_ports_for_e2e_test
  end
end

after_all do |lane|
  clean_up_ports_for_e2e_test if lane == :test_e2e
end

desc 'Starts Sinatra web server'
lane :start_sinatra do
  sh('bundle exec ruby sinatra.rb > sinatra-log.txt 2>&1 &')
end

desc 'Stops Sinatra web server'
lane :stop_sinatra do
  sh("lsof -t -i:#{sinatra_port} | xargs kill -9")
end

desc 'Starts Stream Video Buddy'
lane :start_video_buddy do
  sh("stream-video-buddy auth --record-session")
  sh("stream-video-buddy server --port #{video_buddy_port} > video-buddy-log.txt 2>&1 &")
end

desc 'Stops Stream Video Buddy'
lane :stop_video_buddy do
  sh("lsof -t -i:#{video_buddy_port} | xargs kill -9")
end

desc 'Runs e2e ui tests'
lane :test_e2e do |options|
  next unless is_check_required(sources: sources_matrix[:e2e], force_check: @force_check)

  start_sinatra
  start_video_buddy
end

private_lane :clean_up_ports_for_e2e_test do
  stop_sinatra
  stop_video_buddy
end

private_lane :current_branch do
  ENV['BRANCH_NAME'] || git_branch
end

desc 'Run fastlane linting'
lane :rubocop do
  next unless is_check_required(sources: sources_matrix[:ruby], force_check: @force_check)

  sh('bundle exec rubocop')
end

lane :sources_matrix do
  {
    e2e: ['demo-app', 'stream-video-android-bom', 'stream-video-android-core', 'stream-video-android-previewdata', 'stream-video-android-ui-compose', 'stream-video-android-ui-core', 'stream-video-android-ui-xml'],
    ruby: ['fastlane']
  }
end
