name: Build and Upload AAB

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Build and Upload AAB
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: GetStream/android-ci-actions/actions/setup-java@main

      - name: Prepare environment
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > .sign/release.keystore.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch .sign/release.keystore.asc > .sign/release.keystore
          echo "${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}" > .sign/keystore.properties.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch .sign/keystore.properties.asc > .sign/keystore.properties
          echo "${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}" > .sign/service-account-credentials.json.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch .sign/service-account-credentials.json.asc > .sign/service-account-credentials.json
          echo "${{ secrets.ENV_PROPERTIES }}" > .env.properties

      - name: Build release bundle
        run: ./gradlew bundleRelease --stacktrace

      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: demo-app/build/outputs/bundle/productionRelease/demo-app-production-release.aab
