name: Publish Compose UI snapshot tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_dogfooding_sample_app:
    name: Run Compose UI tests and Publish UI snapshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11

      - name: Prepare environment
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > .sign/release.keystore.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch .sign/release.keystore.asc > .sign/release.keystore
          echo "${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}" > .sign/keystore.properties.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch .sign/keystore.properties.asc > .sign/keystore.properties
          echo "${{ secrets.ENV_PROPERTIES }}" > .env.properties

      - name: Check out code
        uses: actions/checkout@v3.1.0
        with:
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11

      - name: Generate Paparazzi snapshots HTML docs
        run: ./gradlew recordPaparazziDebug

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.STREAM_CI_TOKEN }}
          publish_dir: ./stream-video-android-compose/build/reports/paparazzi
          publish_branch: compose-snapshot