name: Publish Docusaurus to staging

on:
  push:
    branches:
      - develop
    paths:
      - 'docusaurus/**'

jobs:
  push_docusaurus:
    name: Publish Docusaurus docs to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 16
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: push
        uses: GetStream/push-stream-chat-docusaurus-action@main
        with:
          target-branch: 'staging'
          destination-repository-name: 'stream-video-docusaurus'
        env:
          DOCUSAURUS_GH_TOKEN: ${{secrets.DOCUSAURUS_GH_TOKEN}}
