name: Publish Docusaurus to staging

on:
  push:
    paths:
      - 'docusaurus/**'
      - '.github/workflows/docusaurus.yml'
      
jobs:
  push_docusaurus:
    name: Publish Docusaurus docs to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: push
        uses: GetStream/push-stream-chat-docusaurus-action@main
        with:
          target-branch: ${{ github.ref == 'refs/heads/main' && 'main' || 'staging' }}
          cli-target-branch: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
          destination-repository-name: 'stream-video-docusaurus'
          source-directory: 'docusaurus'
        env:
          DOCUSAURUS_GH_TOKEN: ${{secrets.DOCUSAURUS_GH_TOKEN}}
