name: E2E Build

on:
  workflow_call:

env:
  BUILD_CACHE_AWS_REGION: ${{ secrets.BUILD_CACHE_AWS_REGION }}
  BUILD_CACHE_AWS_BUCKET: ${{ secrets.BUILD_CACHE_AWS_BUCKET }}
  BUILD_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_CACHE_AWS_ACCESS_KEY_ID }}
  BUILD_CACHE_AWS_SECRET_KEY: ${{ secrets.BUILD_CACHE_AWS_SECRET_KEY }}

jobs:
  build:
    name: compose apks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: GetStream/android-ci-actions/actions/setup-java@main
      - uses: GetStream/android-ci-actions/actions/enable-kvm@main
      - uses: ./.github/actions/setup-ruby
      - uses: GetStream/android-ci-actions/actions/gradle-cache@main
      - name: Build apks
        run: bundle exec fastlane build_e2e_test
        timeout-minutes: 30
      - name: Upload apks
        uses: actions/upload-artifact@v4.4.3
        with:
          name: apks
          path: |
            demo-app/build/outputs/apk/e2etesting/debug/*.apk
            demo-app/build/outputs/apk/androidTest/e2etesting/debug/*.apk
