name: Internal App Distribute CI

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  distribute_stream_video_calls_to_google_play:
    name: Distribute Stream Video Calls to Google Play
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-java
      - name: Prepare environment
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > .sign/release.keystore.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch .sign/release.keystore.asc > .sign/release.keystore
          echo "${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}" > .sign/keystore.properties.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch .sign/keystore.properties.asc > .sign/keystore.properties
          echo "${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}" > .sign/service-account-credentials.json.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch .sign/service-account-credentials.json.asc > .sign/service-account-credentials.json
          echo "${{ secrets.ENV_PROPERTIES }}" > .env.properties
      - name: Publish Bundle
        run: bash ./gradlew publishBundle --stacktrace