# .github/workflows/pr-quality-check.yml (caller)
name: PR cleanup

on:
  schedule:
    - cron: "0 7 * * 1"  # every Monday 09:00 CEST (UTC+2)
  workflow_dispatch:


permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr-checklist:
    uses: GetStream/android-ci-actions/.github/workflows/pr-clean-stale.yaml@main
    secrets: inherit
