name: Publish New Version

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: "Type of version bump to perform"
        options:
          - patch
          - minor
          - major

jobs:
  pre_release_check:
    name: Pre release check
    runs-on: ubuntu-24.04
    environment: 'publish'
    steps:
      - name: Check
        id: pre_release_check_step
        run: echo "Pre release check"
  publish:
    needs: pre_release_check
    uses: GetStream/android-ci-actions/.github/workflows/release-new-version.yml@main
    environment: 'publish'
    with:
      ref: "develop"
      bump: ${{ inputs.bump }}
      file-path: ./buildSrc/src/main/kotlin/io/getstream/video/android/Configuration.kt
      excluded-modules: "demo-app,tutorials:tutorial-video,tutorials:tutorial-audio"
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
      STREAM_PUBLIC_BOT_TOKEN: ${{ secrets.STREAM_PUBLIC_BOT_TOKEN }}
